global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MinIO metrics
  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s

  # Flink JobManager metrics
  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['jobmanager:9249']
    scrape_interval: 30s

  # Flink TaskManager metrics
  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['taskmanager:9249']
    scrape_interval: 30s